# Generated by Django 3.0.8 on 2020-08-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_post_thumbnails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('sub_headline', models.CharField(blank=True, max_length=200, null=True)),
                ('validation_id', models.CharField(max_length=200)),
                ('thumbnails', models.ImageField(blank=True, default='desktop wallpaper.jpg', null=True, upload_to='images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(null=True, to='mainsite.Tag')),
            ],
        ),
    ]
